language: node_js
node_js:
  - 7
sudo: required
services:
  - docker
before_install:
  - docker build -t joydesigner/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joydesigner/docker-react npm run test