language: ruby
rvm:
  - 2.2
  - jruby
  - truffleruby
  - 2.0.0-p247
sudo: required
services:
  - docker

before_install:
  - docker build -t joydesigner/docker-react -f Dockerfile.dev .

script:
  - docker run joydesigner/docker-react npm run test -- --coverage